// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Koppla_kurs_och_dokument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Koppla_kurs_och_dokument));
        
        string IMigrationMetadata.Id
        {
            get { return "201606300856061_Koppla_kurs_och_dokument"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
