// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeddatatypeforDocumentTypefromstringtoDocumentTypeinDocumentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeddatatypeforDocumentTypefromstringtoDocumentTypeinDocumentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201607081348302_Changed datatype for DocumentType from string to DocumentType in DocumentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
